plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0
relative_links:
  enabled: true
  collections: true
markdown: GFM
include:
  - output.txt
  - index.md
